export const ERROR_CODES = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
  AUTH_NICKNAME_EXISTS: 'AUTH_NICKNAME_EXISTS',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_INACTIVE: 'USER_INACTIVE',

  // Work
  WORK_NOT_FOUND: 'WORK_NOT_FOUND',
  WORK_NOT_PUBLISHED: 'WORK_NOT_PUBLISHED',

  // Episode
  EPISODE_NOT_FOUND: 'EPISODE_NOT_FOUND',
  EPISODE_NOT_PURCHASED: 'EPISODE_NOT_PURCHASED',
  EPISODE_ALREADY_PURCHASED: 'EPISODE_ALREADY_PURCHASED',

  // Payment
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_ALREADY_PROCESSED: 'PAYMENT_ALREADY_PROCESSED',
  INVALID_PAYMENT_AMOUNT: 'INVALID_PAYMENT_AMOUNT',

  // AI
  AI_GENERATION_FAILED: 'AI_GENERATION_FAILED',
  AI_GENERATION_TIMEOUT: 'AI_GENERATION_TIMEOUT',
  AI_RATE_LIMIT_EXCEEDED: 'AI_RATE_LIMIT_EXCEEDED',

  // General
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface ApiError {
  statusCode: number;
  code: ErrorCode;
  message: string;
  details?: Record<string, unknown>;
}
